



create table ACCOUNTS(PRIVATE_KEY VARCHAR(40), ADDRESS VARCHAR(40), Full_Name CHAR(50), UID INT(10) NOT NULL auto_increment PRIMARY KEY);

create table CONTRACT(CONTRACT_NAME VARCHAR(30) NOT NULL , BYTECODE VARCHAR(30000) NOT NULL , ABI VARCHAR(30000) NOT NULL , CONTRACT_ID INT NOT NULL AUTO_INCREMENT, UID INT(10) CONSTRAINT C4   FOREIGN KEY REFERENCES ACCOUNTS(UID));



create table ACCOUNTS(PRIVATE_KEY VARCHAR(40), ADDRESS VARCHAR(40), Full_Name CHAR(50), UID INT(10)  NOT NULL auto_increment PRIMARY KEY);

create table CONTRACT(CONTRACT_NAME VARCHAR(30) NOT NULL , BYTECODE VARCHAR(3000) NOT NULL , ABI VARCHAR(3000) NOT NULL , CONTRACT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, UID INT(10), FOREIGN KEY(UID) REFERENCES ACCOUNTS(UID));

SELECT * from Deployed;
create table Deployed(CONTRACT_ID INT,Contract_Address VARCHAR(32), DEPLOYER INT(10),Network_Name CHAR(10),FOREIGN KEY(DEPLOYER) REFERENCES ACCOUNTS(UID),FOREIGN KEY(CONTRACT_ID) REFERENCES CONTRACT(CONTRACT_ID) );


